### ISSUE TITLE
ERROR: Description = Invalid namespace (IS.bookmarks.html parser)

### ISSUE THREAD

**Issue by UltimateBoi** [Illegal-Services/Illegal_Services#11]
![image](https://user-images.githubusercontent.com/63293118/154836073-a035d622-564c-403f-8336-b6a5854d57f2.png)
for some reason this happens. Please tell me a fix?

Oh and also, it seems to be 1 big list now not just conveniently organised:
![image](https://user-images.githubusercontent.com/63293118/154836096-81dbbbe1-886a-4020-982d-4491887cbd70.png)
is this intentional or not?

**Comment by UltimateBoi** [comment]
Oh and here is a video of what happens when i go back: 
https://anonfiles.com/DbCegfJ0x3/Illegal_Services_AOicQaxp9D_mp4

**Comment by Illegal-Services** [comment]
> "for some reason this happens. Please tell me a fix?"
I believe this is due to the time parsing function from Illegal Services.
I'm not sure if I'll be able to even fix that. But i will try to make it's error messages more precise in a future update.

> "is this intentional or not?"
Yes, this is intentional. It is the new disposition of menus since v6.0

> "Oh and here is a video of what happens when i go back"
I can't exactly see what's going on because some parts are missing from the screen recording video.
The "BACK" button like it's name says, is going to the previous folder, and if many PATH's are displaying, it will fetch the last folder that is present in both PATH's.

**Comment by UltimateBoi** [comment]
Ok thanks, if possible, could you make it an option to go back to the previous menu style because it was much cleaner and easier to see.

**Comment by Illegal-Services** [comment]
Sorry, I won't restore the old layout. The reason I changed everything in v6.0 is because the database from Illegal Services contain ~1000 websites , and believe me it is pain to update that hard-coded manually everyday's. It just wasn't an option for me to continue the old layout anymore... I agree that it was nicer before, but sadly it have to stay like that if we want the project to grow up and get a bigger growing database of websites.

Okay so about the bug in this issue, I have done some research, and I believe WMIC.EXE is depracted on Windows 11 and the both errors you got are directly caused from this command:
`wmic os get Localdatetime /value`
Please can you run it and let me know the output from it?

**Comment by Illegal-Services** [comment]
Also, if you want a clean solution to keep using Illegal Services website database, you might be very interested in importing IS.bookmarks.html file in your browser bookmarks. I didn't yet made a tutorial page on how to make that, but it's planned for soon...

**Comment by UltimateBoi** [comment]
How would i import it?

**Comment by Illegal-Services** [comment]
Just Google something like: "how to import bookmarks in internet browser on {your OS system}."

**Comment by UltimateBoi** [comment]
windows 11 obviously

**Comment by UltimateBoi** [comment]
But its a html file, how am i supposed to import it?

**Comment by Illegal-Services** [comment]
On Windows 11, so for Google Chrome:
https://support.google.com/chrome/answer/96816?hl=en

for Mozilla Firefox:
https://support.mozilla.org/en-US/kb/import-bookmarks-html-file

**Comment by Illegal-Services** [comment]
Normally, I successfully corrected the problem with this code in [v6.1](https://github.com/Illegal-Services/Illegal_Services/releases/tag/v6.1):
https://github.com/Illegal-Services/Illegal_Services/commit/70da50b962b87ba9f27f522a345658ba848bfb19#diff-30bc95eef2f06036bdea79fd3cda4006fe08f96c9861cc90060eb44f88d4338cR4455
